spring:
  profiles:
    active: learnerlab
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: ${AWS_ACCESS_KEY:}
        secret-key: ${AWS_SECRET_KEY:}

# DynamoDB Configuration
dynamodb:
  endpoint: ${DYNAMODB_ENDPOINT:https://dynamodb.us-east-1.amazonaws.com}
  region: ${AWS_REGION:us-east-1}

# Logging
logging:
  level:
    com.tdse: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
