serverless:
  frameworkVersion: '3'
  provider:
    name: aws
    runtime: java17
    region: us-east-1
    timeout: 30
    memorySize: 512
    environment:
      SPRING_PROFILES_ACTIVE: aws
  package:
    artifact: target/user-service-1.0.0.jar
    individually: true

functions:
  userService:
    handler: com.tdse.twitter.microservices.user.UserLambdaHandler::handleRequest
    events:
      - http:
          path: /users/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /users
          method: ANY
          cors: true
